# Generated by Django 3.2.3 on 2021-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('modelNameOne', models.CharField(max_length=100)),
                ('modelNoOne', models.CharField(max_length=100)),
                ('modelNameTwo', models.CharField(max_length=100)),
                ('modelNoTwo', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField()),
                ('totalAmount', models.CharField(max_length=20)),
                ('advanceAmount', models.CharField(max_length=20)),
            ],
        ),
    ]
