# Generated by Django 3.1.5 on 2021-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210528_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='custimerId',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='quantityOne',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='quantityTwo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
