# Generated by Django 3.2.3 on 2021-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customerdetails_custimerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='dueAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
