# Generated by Django 3.1.5 on 2021-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customerdetails_dueamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentOnEmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateField()),
            ],
        ),
    ]
