# Generated by Django 3.1.5 on 2021-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210601_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentonemi',
            name='refNo',
            field=models.CharField(max_length=15),
        ),
    ]
