# Generated by Django 3.1.5 on 2021-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210601_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentonemi',
            name='refNo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
