# Generated by Django 3.2.3 on 2021-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210603_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentonemi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
