# Generated by Django 3.1.5 on 2021-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210603_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='techName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicianName', models.CharField(max_length=100)),
                ('disignation', models.CharField(max_length=50)),
                ('contactNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentonemi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
