# Generated by Django 3.2.3 on 2021-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210607_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phoneNo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='partsname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentonemi',
            name='chequeNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentonemi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='techname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
