# Generated by Django 3.2.3 on 2021-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210607_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phoneNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
