# Generated by Django 3.2.3 on 2021-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210607_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='phoneNo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
